---
title: "Picatoste_preproceso"
author: "Alvaro Picatoste"
date: "9 de marzo de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Practica 1

1-. Cargar el fichero de datos en R. Antes de cargar el fichero, se debe inspeccionar que tipo de formato csv es para realizar la lectura apropiada.

```{r}
#Valor decimal separado por "." -> sistema ingles -> read.csv en vez de read.csv2
mydata <- read.csv("2016_raw.csv")
```

2-. Cambiar los nombres de las variables que son muy largos por otros mas cortos (al final del documento se especifica como).

```{r}
#Creo una funcion que inspecciona un vector y si contiene nombres separados por "." acorta automaticamente siguiendo las instrucciones del enunciado.

short.variables <- function(input1, ...){
for (i in 1:length(input1)){
if (!grepl("\\.", (input1)[i])) {
  next } 
  else { 
    separate.words <- strsplit(input1[i], "\\.")
    number.of.words <- length(separate.words[[1]])
    mystring <- c()
    for (jj in 1:number.of.words){
      myletter <- substr(separate.words[[1]][jj], 1,1)
      mystring <- c(mystring, myletter)
    }
    
    input1[i] <- paste(mystring, collapse = "")

    }
  }
return(input1)  
}

#Aplico la funcion al vector que contiene el nombre de las variables

names(mydata)
names(mydata) <- short.variables(names(mydata))
names(mydata)

```

3. Indicar el tipo de variable estadistica de cada variable.

```{r}
#Estudio si las variables son categoricas-cualitativas(nominal u ordinal) o cuantitativas (discreta o continua)

sapply(mydata, class)

cco <- "Categorica-cualitativa-ordinal"
ccn <- "Categorica-cualitativa-nominal"
cnd <- "Cuantitativa Discreta"
cnc <- "Cuantitativa Continua"

mis_categorias <- c(ccn, ccn, cco, cnc, cnc, cnc, cnc, cnc, cnc, cnc, cnc)
print(mis_categorias)

length

as.table(setNames(names(mydata), mis_categorias))


#Estudio con deteniminto HR,HS, GpC
#Happiness Rank aparece como cuantitativa numérica pero debera ser cualitativa ordinal.
#Happiness Score aparece como categórica pero debera ser numerica decimal.
#GDP per capita aparece como categórica pero debera ser numerica decimal.
```